# Generated by Django 4.2.7 on 2023-11-16 12:54

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Category name')),
                ('description', djrichtextfield.models.RichTextField(blank=True, verbose_name='Desc')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('activate', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Tag name')),
                ('uuid', models.UUIDField(verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Category name')),
                ('description', djrichtextfield.models.RichTextField(blank=True, verbose_name='Desc')),
                ('activate', models.BooleanField(default=False, verbose_name='Active')),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(related_name='category_tag', to='catalog.tag'),
        ),
    ]
