# Generated by Django 4.2.7 on 2023-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
