# Generated by Django 4.2.7 on 2023-11-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_goods_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
        migrations.AddField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(related_name='goods_tag', to='catalog.tag'),
        ),
    ]
