# Generated by Django 4.2.7 on 2023-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_tags_goods_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(related_name='category_tag', to='catalog.tag'),
        ),
    ]
