# Generated by Django 4.2.7 on 2023-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_category_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Category name'),
        ),
    ]
