# Generated by Django 4.2.7 on 2023-12-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
